version: "2"
services:
  frontend:
    image: bmeugis/clms-frontend:1.0
    ports:
      - 3000:3000
    environment:
      API_PATH: "http://10.1.0.11:62934/Plone"
      INTERNAL_API_PATH: "http://10.1.0.11:62934/Plone"
      VOLTO_API_PATH: "http://10.1.0.11:62934/Plone"
volumes:
  data:
    driver: local
