version: '3'

services:
  frontend:
    image: docker pull bmeugis/clms-frontend:1.0
    ports:
      - '${FRONTEND:-8000}:3000'
    depends_on:
      - ploneapi
    environment:
      API_PATH: 'http://localhost:62934/Plone'
      INTERNAL_API_PATH: 'http://ploneapi:62934/Plone'

volumes:
  data:
    driver: local
